# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
#  - osx
branches:
  only:
    - master
julia:
  - 1
env:
  - GROUP=Interface
allow_failures:
    - julia: nightly
notifications:
  email: false
script: julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=false)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("DiffEqOperators")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("DiffEqOperators")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
